### ISSUE TITLE
checking Fibre-Channel port

### ISSUE THREAD

**Issue by me-oct** [mkorthof/check_ibm_storwize#1]
Thank you for providing such a useful script.
I don't know if the script is still maintained, but we run this script on the Storwize V3700 with Nagios to monitor the healthiness of the unit.

Recently we had a problem with the fibre-channel port on the V3700, but the script did not detect the error.
The problem was the faulty SFP converter, which disabled one of the fibre-channel ports. The Web GUI manager said that the fibre-channel was not able to operate. The 'lsportfc' command showed that the port status was 'inactive_configured'.
The script checks only the 'OperationalStatus' for Fibre-Channel and would considers the status as OK when the value is 2 (OK) or 10 (Stopped). I guess the OperationalStatus was 10, but the 'StatusDescriptions" attribute was something like 'Port configured inactive' at the time. Unfortunately we did not have a chance to check if this was the case.

Any advice would be very helpful.
Many thanks.

**Comment by mkorthof** [comment]
Hi,

Thanks for your kind words, I've just updated the original script though :)
Funny you mention SFP, I remember we had an issue with that where the storwize would not detect there the port was down (on iSCSI though). IIRC that's why I added a NetworkPort check to the script -- dont think it ever worked for us.

Nowadays I do not work with IBM storage anymore and no longer have access to any device. 

In your case, with FC, we can perhaps try adding a StatusDescriptions check using the [ibm docs](/docs).
Will try to get you a modified version of the script to test.

**Comment by me-oct** [comment]
Great to hear from you, mkorthof.

I found the latest script has been changed much from the previous one.
I understand it still has an issue on detecting a fibre-channel fault.

I look forward to getting a modified version checking StatusDescriptions.
Many thanks.

**Comment by mkorthof** [comment]
Hi @me-oct,

I've looked into the issue and as far as I understand if a fcport is "inactive" it has indeed OperationalStatus "10" ("Stopped"). The GUI will show it as "offline" and lsportfs will show "inactive_configured" (from StatusDescriptions).
As soon as there are IOPS it will become "active_configured".

StatusDescriptions uses OperationalStatus ValueMap so its not useful to check it.

Source:
<https://www.ibm.com/support/pages/fc-ports-show-inactinnveconfigured-if-system-not-use>
<https://www.ibm.com/support/pages/gui-shows-fc-ports-offline-information-about-port-status-lsportfc>

(also added these details to [docs/FCPort.md](docs/FCPort.md))

So I changed status "10" to separate condition which will WARN (like IBM). 
Also did the same for "Unused " btw (status "12" or "inactive_unconfigured"). But it just displays those, no alert.

Output now looks like this:
```
$ ./check_ibm_storwize.pl -H ibm03.example.com -u none -p none -C FCPort -t
TEST1: using mock "../test/FCPort.txt" ..
FC PORT WARNING - NOK:0/OK:5/Stopped:2/Unused:1/Total:8 - node2-p5(inactive_unconfigured) node2-p9(inactive_unconfigured) node2-p12(No Contact)|nok=0;;;; ok=5;;;; stopped=2;;;; unused=1;;;; total=8;;;;
```

Warnings for Stopped can be turned on or off but I guess that is not really needed and they should always be on.

Let me know if this is what you were after.
I'll try to upload this version later this week

**Comment by me-oct** [comment]
Great to hear from you again, Marius.

Thank you for your investigation into the issue and exploring a solution for it.
Yes, warning for the status 'Inactive configured' would be just what we need to detect the faulty FC port, even if the Operational Status is Stopped(10).
It would be very nice if we can have an improved version soon.

Many many thanks.

**Comment by mkorthof** [comment]
> It would be very nice if we can have an improved version soon.

Please test and let me know if it works correctly for you on real hardware:
https://github.com/mkorthof/check_ibm_storwize/blob/dev/libexec/check_ibm_storwize.pl

**Comment by me-oct** [comment]
I appreciate yourfor the fast update.
I will let you know the test result on the Storwize, hopefully this Friday.

**Comment by me-oct** [comment]
Hi Marius,

I have tested the FCPort command of the updated script on the Storwize V3700.
The result was;

FC PORT WARNING - NOK:0/OK:4/Stopped:4/Total:8 - 50050768030EB346(Port unconfigured inactive)500507680312B346(Port unconfigured inactive)50050768030EB347(Port unconfigured inactive)500507680312B347(Port unconfigured inactive)|nok=0;;;; ok=4;;;; stopped=4;;;; total=8;;;;

Is this what you expect?
I think it would be good if we can get an OK result ignoring 'unconfigured inactive' (stopped) ports.

I hope this helps you.

Cheers,

**Comment by mkorthof** [comment]
Hi @me-oct,

> FC PORT WARNING - NOK:0/OK:4/Stopped:4/Total:8 - 50050768030EB346(Port unconfigured inactive)500507680312B346(Port unconfigured inactive)50050768030EB347(Port unconfigured inactive)500507680312B347(Port unconfigured inactive)|nok=0;;;; ok=4;;;; stopped=4;;;; total=8;;;;
> 
> Is this what you expect? I think it would be good if we can get an OK result ignoring 'unconfigured inactive' (stopped) ports.

Thanks for testing. Did not expect that, no -- guess I misinterpreted statuses.

I guess there is at least:

- OperationalStatus=10 (Stopped) with StatusDescriptions='Port unconfigured inactive'
- OperationalStatus=12 (Not installed)
- OperationalStatus=?? (???) with StatusDescriptions='Port configured inactive' (?)

I'll change the script accordingly and readd making alerts optional per status, will try to post updated version in the next few days.

**Comment by mkorthof** [comment]
Updated ver, "Stopped" ports no longer generate warnings:
https://github.com/mkorthof/check_ibm_storwize/blob/dev/libexec/check_ibm_storwize.pl

Example:
```
~/dev/check_ibm_storwize/libexec [git:dev]$ ./check_ibm_storwize.pl -H ibm03.example.com -u none -p none -C FCPort -t
TEST1: using mock "../test/FCPort.txt" ..
FC PORT WARNING - NOK:1/OK:5/Stopped:2/Total:8 - node2-p5(unconf_inactive) 567890012A348(unconf_inactive) NOK:567890012A34B(conf_inactive)|nok=1;;;; ok=5;;;; Stopped=2;;;; total=8;;;;
```

**Comment by me-oct** [comment]
Hi Marius,
Thank you for the new update.
As far as I test it with FCPort command on the running V3700 system with unconfigured ports, it works fine.
The command returns 0 (OK) with the following text.

FC PORT OK - NOK:0/OK:4/Stopped:4/Total:8 - 50050768030EB346(unconf_inactive) 500507680312B346(unconf_inactive) 50050768030EB347(unconf_inactive) 500507680312B347(unconf_inactive)|nok=0;;;; ok=4;;;; Stopped=4;;;; total=8;;;;

I would like to check if it can detect a faulty (configured inactive) FCPort. Do you have any good idea to do it?
Unplugging a fiber cable could emulate a fault, but I don't want to have any risk of failure on the customer's working system.

Anyway, I am going to replace the current nagios monitoring script for  Storwize with the new one.

Many thanks again for your support.

**Comment by mkorthof** [comment]
Hi @me-oct ,

Again thanks for testing. Output looks OK to me too.

According to IBM docs:

> Inactive_Configured  =   An SFP is installed in the fiber port but there is no host device connected to the port or no LUN served down this port's path.

I guess a port without an initiator accessing LUN would be in this state (after x amount of time). So no Hosts mapped and no Volumes configured. And then after the system detects IOPS, it becomes active.

Just guessing tho :)

Happy holidays

**Comment by me-oct** [comment]
Marius,
Much appreciated, indeed.
I wish you happy holidays, too.
